%%{init{"theme":"base","themeCSS":"* {line-height:1.25em!important; font-size:12px; text-align:left!important; } span span{color:#666; font-size:0.9em;}  g[id*=\"A\"] * {font-size:1.01em;}  g[id*=\"V\"] * {color:transparent} .edge-thickness-normal{stroke-width:1px; stroke:#999;} .edge-thickness-thick{stroke-width:1px!important} .edge-pattern-dotted{stroke:transparent} mark {background-color:grey; color:white; display:block; text-align:center!important; padding:5px 10px; border-radius:15px}","themeVariables":{"secondaryColor":"transparent","primaryColor":"transparent","primaryBorderColor":"transparent"},"flowchart":{"htmlLabels":true,"padding":5,"rankSpacing":1,"nodeSpacing":1,"curve":"linear"}} }%%
flowchart LR

A[<mark>Plan <br>du cours</mark>]

B1[<b>Séquence 1 :</b></b><br> Éthique et <br> philosophie<br>  morale]
B2[<b>Séquence 2 :</b><br> Philosophie <br> de l'esprit]
B3[<b>Séquence 3 :</b><br> Philosophie<br> de la culture]
B4[<b>Séquence 4 :</b><br> Philosophie<br>sociale et <br>politique]
B5[<b>Séquence 5 :</b><br>Épistémologie <br>et métaphysique]

A --- B1 & B2 & B3 & B4 & B5

B1 --- C1 & C2
B2 --- C3 & C4
B3 --- C5 & C6 & C7
B4 --- C8 & C9
B5 --- C10 & C11

C1["<i>Chapitre 1 :</i> Le bonheur<br><span>(Le bonheur, le temps)</span>"]
C2["<i>Chapitre 2 :</i> La morale<br><span>(La morale, le devoir,<br>la nature)</span>"]

C3["<i>Chapitre 3 :</i> Le libre arbitre<br><span>(La liberté, l'inconscient)</span>"]
C4["<i>Chapitre 4 :</i> L'identité personnelle<br><span>(L'existence humaine, la  conscience)</span>"]

C5["<i>Chapitre 5 :</i> L'art<br><span>(L'art, la culture)</span>"]
C6["<i>Chapitre 6 :</i> La technique<br><span>(La technique, la<br>culture, le travail,<br>la nature, la liberté)</span>"]
C7["<i>Chapitre 7 :</i> Le langage<br><span>(Le langage, la culture)</span>"]

C8["<i>Chapitre 8 :</i> Œuvre suivie<br><span>(La politique, la liberté,<br> l'#Eacute;tat, la justice)</span>"]
C9["<i>Chapitre 9 :</i> La politique<br><span>(La politique, la liberté,<br> l'#Eacute;tat, la justice)</span>"]

C10["<i>Chapitre 10 :</i> La vérité<br><span>(La vérité, la connaissance, <br>la raison, la science)</span>"]
C11["<i>Chapitre 11 :</i> La religion<br><span>(La religion, la vérité, la raison)</span>"]

C1 --- D1a & D1b
C1 -.- V1
C2 --- D2a & D2b
C2 -.- V2
C3 --- D3a & D3b
C3 -.- V3
C4 --- D4a & D4b
C4 -.- V4
C5 --- D5a & D5b
C5 -.- V5
C6 --- D6a & D6b
C6 -.- V6
C7 --- D7a & D7b
C7 -.- V7
C8 --- D8
C8 -.- V8
C9 --- D9a & D9b
C9 -.- V9
C10 --- D10a & D10b
C10 -.- V10
C11 --- D11a & D11b

D1a["Q1 – Pouvons-nous parvenir au bonheur ?"]
D1b["Q2 – Le bonheur est-il le but de l'existence ?"]
D2a["Q1 – Y a-t-il des vérités en morale ?"]
D2b["Q2 – Comment peut-on savoir ce <br>qui est bien et ce qui est mal ?"]
D3a["Q1 – L'expérience de l'action volontaire <br>est-elle une preuve du libre arbitre ?"]
D3b["Q2 – Nos choix sont-ils déterminés par <br>des facteurs que nous ne maîtrisons pas ?"]
D4a["T1 – Locke : la conception <br>mémorielle de l'identité"]
D4b["T2 – Sartre : l'existentialisme"]
D5a["Q1 – L'artiste n'obéit-il à aucune règle ?"]
D5b["Q2 – Qu'est-ce que l'art nous apporte ?"]
D6a["Q1 – La technique permet-elle <br>de maîtriser la nature ?"]
D6b["Q2 – Le développement technique <br>transforme-t-il les êtres humains ?"]
D7a["Q1 – Le langage permet-il de tout dire ?"]
D7b["Q2 – Le langage exerce-t-il<br> un pouvoir sur nous ?"]
D8["Rousseau, <i>Discours sur <br>l'économie politique</i>"]
D9a["Q1 – De quel droit l'État <br>exerce-t-il un pouvoir sur nous ?"]
D9b["Q2 – Qu'est-ce que la justice sociale ?"]
D10a["Q1 – Peut-on dire <br>« à chacun sa vérité » ?"]
D10b["Q2 – Faut-il douter de tout ?"]
D11a["Q1 – "]
D11b["Q2 – "]


D1a --- E1a1 & E1a2 & E1a3
D1b --- E1b1

E1a1["Q1a – Savons-nous ce qu'est le bonheur ? <br><span>(Kant vs. les sagesses antiques)</span>"]
E1a2["Q1b – Le désir nous fait-il nécessairement souffrir ? <br><span>(Schopenhauer vs. Épicure)</span>"]
E1a3["Q1c – Que pouvons-nous face au tragique de l'existence ? <br><span>(Pascal vs. le stoïcisme)</span>"]

E1b1["<span>Simone de Beauvoir vs. J.S. Mill</span>"]

D2a --- E2a1 & E2a2
D2b --- E2b1 & E2b2 & E2b3

E2a1["Q1a - La morale est-elle subjective ? <br><span>Subjectivisme moral vs. objectivisme moral</span>"]
E2a2["Q1b – La morale est-elle relative à chaque culture ? <br><span>Relativisme moral vs. universalisme moral</span>"]

E2b1["Q2a - La morale repose-t-elle sur le sentiment ou la raison ? <br><span>Sentimentalisme moral (Rousseau) vs. rationalisme moral</span>"]